---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install required packages
  package:
    name:
      - curl
      - tar
      - wget
      - git
      - net-tools
      - python3
      - python3-pip
    state: present

- name: Set up system limits for TiKV and SurrealDB
  pam_limits:
    domain: '*'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  loop:
    - { limit_type: soft, limit_item: nofile, value: 1000000 }
    - { limit_type: hard, limit_item: nofile, value: 1000000 }
    - { limit_type: soft, limit_item: nproc, value: 64000 }
    - { limit_type: hard, limit_item: nproc, value: 64000 }

- name: Set timezone
  timezone:
    name: UTC