---
- name: Create TiKV user
  user:
    name: "{{ tikv_user }}"
    group: "{{ tikv_group }}"
    system: yes
    create_home: no
    shell: /sbin/nologin

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ tikv_user }}"
    group: "{{ tikv_group }}"
    mode: '0755'
  loop:
    - "{{ tikv_data_dir }}"
    - "{{ pd_data_dir }}"
    - "/usr/local/bin"

- name: Install TiUP
  shell: |
    curl -sSf {{ tiup_mirror }}/install.sh | sh
  args:
    creates: ~/.tiup/bin/tiup

- name: Add TiUP to PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=/root/.tiup/bin:$PATH'
    create: yes

- name: Install TiKV components
  shell: |
    source ~/.bashrc
    tiup install pd tikv playground

- name: Create TiKV startup script
  template:
    src: tiup.sh.j2
    dest: /usr/local/bin/start-tikv.sh
    mode: '0755'
    owner: "{{ tikv_user }}"
    group: "{{ tikv_group }}"
