---
- name: Install TiUP
  shell: |
    curl -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
  args:
    creates: ~/.tiup/bin/tiup

- name: Add TiUP to PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=/root/.tiup/bin:$PATH'
    create: yes

- name: Start TiKV playground
  shell: |
    source ~/.bashrc
    tiup playground --tag surrealdb --mode tikv-slim --pd 1 --kv 1 --host 0.0.0.0
  async: 300
  poll: 0
  when: inventory_hostname in groups['pd_servers']
